title: "GlennMurray Published (GLMR)"
description: "Lecture Note in Fundametal AI â€” current issue: Searching Strategy and Its Application."
theme: minima
# Enable relative links for assets outside docs/
relative_links:
  enabled: true
  collections: true
